:stylesdir: css
:stylesheet: obsidian.css
:imagesdir: images
:nofooter:
:title: Obsidian Level Generator
:toc: left
:toclevels: 1
:toc-title: 
:favicon: images/favicon.png

== About

OBSIDIAN is a community continuation of https://oblige.sourceforge.net[OBLIGE Level Maker], originally by Andrew Apted. It generates levels for idTech 0 (Wolfenstein-3D, etc) and idTech 1 (Doom, etc) games. 

=== Notable differences from OBLIGE

* Base content merged with the ObAddon content pack, along with brand new prefabs, themes and shape grammars
* GUI overhaul: Sliders, checkboxes, top bar menu, and theming are now built in
* UDMF map output option for ports that support it
* Improved RNG with 64-bit seed lengths and the ability to use arbitrary strings as seeds
* Ability to support Vanilla Doom and its engine limits by using the bundled SLUMP map generator
* "Surprise Me" option for randomization of selected settings
* Optional PK3/ZIP compression of generated WADs
* Migration from Lua to LuaJIT for greatly improved build speeds
* First-run tutorial for users not accustomed to the program or its interface
* More robust batch/CLI mode
* Ability to compile without a graphical interface for server/headless environments if desired
* Option to save an animated GIF of the level building process
* Integration of previous versions of Oblige to offer increased variety in level layouts and composition
* Improved internationalization support, along with a nearly complete Russian locale translation file included

=== Currently Supported Games

* Doom 1 / The Ultimate Doom/ Doom 2 / Final Doom
* Heretic
* Chex Quest 3
* HacX 1.2
* Harmony
* Hexen
* Strife
* Wolfenstein 3-D / Spear of Destiny
* Super Noah's Ark 3-D

=== Currently Supported Platforms

* Windows 32/64-bit, x86 architecture
* Linux 32/64-bit, x86 and ARM architectures
* BSD 32/64-bit, x86 and ARM architectures
* MacOS 64-bit, x86 architecture (tested with Github CI builds only)